#!/bin/bash
# Reads urls and names from a files and downloads them from youtube, and then converts them into mp3 files.

lineCount=1
FILENAME=''
URL=''

# Location Files save to
DIR='/home/ryan/owncloud/'
# Location of Download List
CONVERTLIST='/home/ryan/Dropbox/convertList.txt'



while read line
do
let evenCheck=$"(($lineCount)%2)"

if [ $evenCheck -eq 0  ]
	then
	# set url variable name
	URL=$line
	
	# Download video
	youtube-dl --output="$DIR/.$FILENAME" --format=18 "$URL"
	# Convert video to audio file.
	ffmpeg -i "$DIR/.$FILENAME" -acodec libmp3lame -ac 2 -ab 128k -vn -y "$DIR/$FILENAME.mp3"	
	# Remove video download
	rm "$DIR/.$FILENAME"

else
	# Set filename variable
	FILENAME=$line
fi

lineCount=`expr $lineCount + 1`
done < $CONVERTLIST
