CFLAGS=-Wall -g


all: ex1 ex3 ex4 ex5 ex8

rebuild: clean all

ex1:
	cc -Wall -g ex1.c -o ex1
ex3:
	cc -Wall -g ex3.c -o ex3
ex4:
	cc -Wall -g ex4.c -o ex4
ex5:
	cc -Wall -g ex5.c -o ex5
ex8:
	cc -Wall -g ex8.c -o ex8
clean:
	rm -f ex1 ex3 ex4 ex5 ex8
