CFLAGS=-Wall -g

all: ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9

rebuild: clean all

ex1:
	cc -Wall -g ex1.c -o ex1
ex3:
	cc -Wall -g ex3.c -o ex3
ex4:
	cc -Wall -g ex4.c -o ex4
ex5:
	cc -Wall -g ex5.c -o ex5
ex6:
	cc -Wall -g ex6.c -o ex6
ex7:
	cc -Wall -g ex7.c -o ex7
ex8:
	cc -Wall -g ex8.c -o ex8
ex9:
	cc -Wall -g ex9.c -o ex9
clean:
	rm -f ex1 ex3 ex4 ex5 ex6 ex7 ex8 ex9

